import Head from "next/head";
import Nav from "@/components/Nav";
import Image from "next/image";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { faMinus, faPlus } from "@fortawesome/free-solid-svg-icons";
import { useShoppingCart } from "@/context/ShoppingCartContext";
import { useNavHeight } from "../context/NavHeightContext";

type Item = {
  id: number;
  title: string;
  price: number;
  description: string;
  category: string;
  image: string;
  rating: {
    rate: number;
    count: number;
  };
};

type Props = {
  items: Item[];
};

export default function Store({ items }: Props) {
  const {
    getItemQuantity,
    increaseCartQuantity,
    decreaseCartQuantity,
    removeFromCart,
  } = useShoppingCart();
  const navHeight = useNavHeight();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main
        style={{ marginTop: navHeight }}
        className="grid grid-cols-1 place-items-center p-8 gap-8 md:grid-cols-3"
      >
        {items.map((item) => {
          const { id, title, price, description, category, image, rating } =
            item;
          const quantity = getItemQuantity(id);
          return (
            <div
              className="w-full p-4 space-y-4 rounded-lg bg-veryLightGray"
              key={id}
            >
              <div className="h-48">
                <Image src={image} alt={title} height={100} width={100} />
              </div>
              <h1 className="truncate">{title}</h1>
              <h2 className="font-bold">{`$${price}`}</h2>
              {quantity === 0 ? (
                <div className="w-full">
                  <button
                    onClick={() => increaseCartQuantity(id)}
                    className="w-full bg-blue hover:bg-darkerBlue text-white font-bold py-2 px-4 rounded"
                  >
                    + Add to Cart
                  </button>
                </div>
              ) : (
                <div className="space-y-4">
                  <div className="flex justify-center space-x-4">
                    <button>
                      <FontAwesomeIcon
                        icon={faMinus}
                        className="bg-blue text-white p-2"
                        onClick={() => decreaseCartQuantity(id)}
                      />
                    </button>
                    <p>{quantity} in cart</p>
                    <button>
                      <FontAwesomeIcon
                        icon={faPlus}
                        className="bg-blue text-white p-2"
                        onClick={() => increaseCartQuantity(id)}
                      />
                    </button>
                  </div>
                  <div className="flex justify-center">
                    <button
                      onClick={() => removeFromCart(id)}
                      className="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded"
                    >
                      Remove
                    </button>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </main>
    </>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();
  return {
    props: {
      items: data,
    },
  };
}
